### ISSUE TITLE
ReviewDB crashes Enmity if you click on a review warning.

### ISSUE THREAD

**Issue by jackmio32** [StupidityDB/EnmityPlugin#1]
Running Enmity on ~~154.0~~ EDIT: meant to say 164.0, and pressing the "Warning" box shown at the top of the reviews area for some users, like Carl-bot, causes Enmity to immediately crash.

**Comment by RGBCube** [comment]
@spinfal @acquitelol

**Comment by acquitelol** [comment]
154 is an extremely old version, if you mean 164 then I believe that you're an old version of ReviewDB as that was fixed a long time ago. Could you provide some more information, such as the plugin version & hash, your discord build number (not the clean number, looks something like 41226) and anything else that you think may be useful? Thanks.

**Comment by jackmio32** [comment]
> 154 is an extremely old version, if you mean 164 then I believe that you're an old version of ReviewDB as that was fixed a long time ago. Could you provide some more information, such as the plugin version & hash, your discord build number (not the clean number, looks something like 41226) and anything else that you think may be useful? Thanks.

Sorry, yes I meant 164.0. This is the debug information I got from the plugin:
[ReviewDB] Debug Information
> Plugin Version: 1.7.9
> Plugin Build: 1.2.0
> Discord Build: 164.0 (39516)
> Software Version: 15.1
> Device:  iPhone 8

**Comment by jackmio32** [comment]
I just checked this repo and realized I'm using an outdated version, and now the issue is fixed. 
However, I have a unrelated quick question: Does this plugin work on BetterDiscord? If not, is there any plans to port it?

**Comment by spinfal** [comment]
> I just checked this repo and realized I'm using an outdated version, and now the issue is fixed. However, I have a unrelated quick question: Does this plugin work on BetterDiscord? If not, is there any plans to port it?

Sorry for the super late reply, there is a BetterDiscord plugin: https://github.com/mantikafasi/ReviewDBIttai
However, it may be broken.
